In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [8]:
def select_all_tasks(conn):
    """
    Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members!:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name, SUM(CASE WHEN B.memid = 0 THEN B.slots * F.guestcost
                        WHEN B.memid <> 0 THEN B.slots * F.membercost
                   END) AS total_revenue
        FROM FACILITIES AS F
        INNER JOIN BOOKINGS AS B ON F.facid = B.facid
        GROUP BY f.name
        HAVING total_revenue < 1000
        ORDER BY total_revenue;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [11]:
def select_all_tasks(conn):
    """
    Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order :
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT M1.surname AS member_surname, M1.firstname AS member_firstname,
            M2.surname AS recommender_surname, M2.firstname AS recommender_firstname
        FROM MEMBERS AS M1
        INNER JOIN MEMBERS AS M2 ON M1.recommendedby = M2.memid
        ORDER BY M2.surname, M2.firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Sarwin', 'Ramnaresh', 'Bader', 'Florence')
('Coplin', 'Joan', 'Baker', 'Timothy')
('Genting', 'Matthew', 'Butters', 'Gerald')
('Baker', 'Timothy', 'Farrell', 'Jemima')
('Pinker', 'David', 'Farrell', 'Jemima')
('Rumney', 'Henrietta', 'Genting', 'Matthew')
('Jones', 'Douglas', 'Jones', 'David')
('Dare', 'Nancy', 'Joplette', 'Janice')
('Jones', 'David', 'Joplette', 'Janice')
('Hunt', 'John', 'Purview', 'Millicent')
('Boothe', 'Tim', 'Rownam', 'Tim')
('Joplette', 'Janice', 'Smith', 'Darren')
('Butters', 'Gerald', 'Smith', 'Darren')
('Owen', 'Charles', 'Smith', 'Darren')
('Smith', 'Jack', 'Smith', 'Darren')
('Mackenzie', 'Anna', 'Smith', 'Darren')
('Worthington-Smyth', 'Henry', 'Smith', 'Tracy')
('Purview', 'Millicent', 'Smith', 'Tracy')
('Crumpet', 'Erica', 'Smith', 'Tracy')
('Baker', 'Anne', 'Stibbons', 'Ponder')
('Bader', 'Florence', 'Stibbons', 'Ponder')
('Stibbons', 'Ponder', 'Tracy', 'Burton')

In [12]:
def select_all_tasks(conn):
    """
    Q12: Find the facilities with their usage by member, but not guests :
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT B.facid, F.name, COUNT(B.memid) AS usage
        FROM BOOKINGS AS B
        INNER JOIN FACILITIES AS F ON B.facid = F.facid
        WHERE B.memid <> 0
        GROUP BY B.facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 308)
(1, 'Tennis Court 2', 276)
(2, 'Badminton Court', 344)
(3, 'Table Tennis', 385)
(4, 'Massage Room 1', 421)
(5, 'Massage Room 2', 27)
(6, 'Squash Court', 195)
(7, 'Snooker Table', 421)
(8, 'Pool Table', 783)

In [15]:
def select_all_tasks(conn):
    """
    Q13: Find the facilities usage by month, but not guests :
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT strftime('%m', B.starttime) AS months, COUNT(B.memid) AS usage
        FROM BOOKINGS AS B
        INNER JOIN FACILITIES AS F ON B.facid = F.facid
        WHERE B.memid <> 0
        GROUP BY strftime('%m', B.starttime);
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 480)
('08', 1168)
('09', 1512)